services:
  - type: worker
    name: discordbot-mirror
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: NODE_VERSION
        value: 20
